const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
sgMail.setSubstitutionWrappers('{{', '}}');

const fs = require("fs");

pathToAttachment = `${__dirname}/YAPNEWSLETTER.pdf`;
attachment = fs.readFileSync(pathToAttachment).toString("base64");



const msg = {
    from: "newsletters@m2p.in",
    subject: "subject",
    text: "text",
    html: "<strong></strong>",
    templateId: 'd-ba2829d1f2c54242ad785f7c6e691c19',
    substitutionWrappers: ['{{', '}}'],
    attachments: [
        {
          content: attachment,
          filename: "YAPNEWSLETTER.pdf",
          type: "application/pdf",
          disposition: "attachment"
        }
      ],
  

    personalizations: [
      { to: 'ravi@brokerage-free.in',dynamic_template_data: { first_name: "Ravi"}, },
{ to: 'bharat@loconav.com',dynamic_template_data: { first_name: "Bharat"}, },
{ to: 'vignesh.elango@npci.org.in',dynamic_template_data: { first_name: "Vignesh"}, },
{ to: 'sankaran.g@cityunionbank.in',dynamic_template_data: { first_name: "Sankaran.G"}, },
{ to: 'tkarthik@csb.co.in',dynamic_template_data: { first_name: "KARTHIK"}, },
{ to: 'damodara@dcbbank.com',dynamic_template_data: { first_name: "Damodar"}, },
{ to: 'jayesh.patil@idfcfirstbank.com',dynamic_template_data: { first_name: "Jayesh"}, },
{ to: 'sudheer.naidu@npci.org.in',dynamic_template_data: { first_name: "Sudheer"}, },
{ to: 'support13.corpsales@qwikcilver.com',dynamic_template_data: { first_name: "Komarla"}, },
{ to: 'harsha.vardhan@novopay.in',dynamic_template_data: { first_name: "Harsha"}, },
{ to: 'abhishek.mody@gmail.com',dynamic_template_data: { first_name: "Abhishek"}, },
{ to: 'nandakumar.sridharan@tvscredit.com',dynamic_template_data: { first_name: "Nandakumar"}, },
{ to: 'keerthana@m2p.in',dynamic_template_data: { first_name: "Keerthana Ramachandran"}, },
{ to: 'prmallic@visa.com',dynamic_template_data: { first_name: "Mallick,"}, },
{ to: 'no-reply@microsoft.com',dynamic_template_data: { first_name: "MyAnalytics"}, },
{ to: 'varun@m2p.in',dynamic_template_data: { first_name: "Varun Selvaraj"}, },
{ to: 'kuru@m2p.in',dynamic_template_data: { first_name: "Kurukshetran Thanikachalam"}, },
{ to: 'arun@m2p.in',dynamic_template_data: { first_name: "Arunkumar Chellapandian"}, },
{ to: 'abhishek.miglani@indifi.com',dynamic_template_data: { first_name: "Abhishek"}, },
{ to: 'richmond@paysack.com',dynamic_template_data: { first_name: "Richmond"}, },
{ to: 'keshav.mishra@savvyapp.in',dynamic_template_data: { first_name: "Keshav"}, },
{ to: 'a_rajendrakumar@equitasbank.com',dynamic_template_data: { first_name: "Rajendra"}, },
{ to: 'do-not-reply@trello.com',dynamic_template_data: { first_name: "Trello"}, },
{ to: 'bosky@bon.pe',dynamic_template_data: { first_name: "Bosky"}, },
{ to: 'badusha.badarudeen@go-mmt.com',dynamic_template_data: { first_name: "Badusha"}, },
{ to: 'rahul.jdevkate@yesbank.in',dynamic_template_data: { first_name: "rahul.jdevkate@yesbank.in"}, },
{ to: 'drive-shares-noreply@google.com',dynamic_template_data: { first_name: "Devang"}, },
{ to: 'bharatqr@csb.co.in',dynamic_template_data: { first_name: "BHARAT"}, },
{ to: 'radhika@m2p.in',dynamic_template_data: { first_name: "Radhika Srinivasan"}, },
{ to: 'tss@vct.co.in',dynamic_template_data: { first_name: "Sridhar"}, },
{ to: 'info@postman.com',dynamic_template_data: { first_name: "The"}, },
{ to: 'arun.sharma@loconav.com',dynamic_template_data: { first_name: "Arun"}, },
{ to: 'deepthi.boina@npci.org.in',dynamic_template_data: { first_name: "Deepthi"}, },
{ to: 'svs@massive.org.in',dynamic_template_data: { first_name: "Shailesh"}, },
{ to: 'sanjeev.kumar@esafbank.com',dynamic_template_data: { first_name: "sanjeev"}, },
{ to: 'newsletter@ettech.com',dynamic_template_data: { first_name: "ETtech"}, },
{ to: 'bsathish@m2p.in',dynamic_template_data: { first_name: "SathishKumar B"}, },
{ to: 'baldeepkaur@federalbank.co.in',dynamic_template_data: { first_name: "Baldeep"}, },
{ to: 'sathishkumar@m2p.in',dynamic_template_data: { first_name: "Sathish Kumar S"}, },
{ to: 'kamal.kumar@wepark.in',dynamic_template_data: { first_name: "Kamal"}, },
{ to: 'ankur.piplodiya@rblbank.com',dynamic_template_data: { first_name: "Ankur"}, },
{ to: 'kartik.a@udaan.com',dynamic_template_data: { first_name: "Kartik"}, },
{ to: 'yogesh.desai@npci.org.in',dynamic_template_data: { first_name: "Yogesh"}, },
{ to: 'yogesh.jain@icicibank.com',dynamic_template_data: { first_name: "Yogesh"}, },
{ to: 'ananth@m2p.in',dynamic_template_data: { first_name: "Ananthaboudmanabhan Thanigachalam"}, },
{ to: 'subhasish.das@trukky.com',dynamic_template_data: { first_name: "Subhasis"}, },
{ to: 'govind.mishra@zencon.co.in',dynamic_template_data: { first_name: "Govind"}, },
{ to: 'naren@m2p.in',dynamic_template_data: { first_name: "Naren Viswanath Sundaramoorthy"}, },
{ to: 'swati@m2p.me',dynamic_template_data: { first_name: "Swati"}, },
{ to: 'karthicks@m2p.in',dynamic_template_data: { first_name: "Karthick"}, },
{ to: 'kabiraj.choudhary@paytmbank.com',dynamic_template_data: { first_name: "Kabiraj"}, },
{ to: 'pmo@tvscredit.com',dynamic_template_data: { first_name: "Pmo"}, },
{ to: 'karan.talwar@livquik.com',dynamic_template_data: { first_name: "Karan"}, },
{ to: 'ramesh.vijayakumar@lvbank.in',dynamic_template_data: { first_name: "Ramesh"}, },
{ to: 'sanjeevi.h@tvscredit.com',dynamic_template_data: { first_name: "Sanjeevi"}, },
{ to: 'yogesh.jarad@sarvatra.in',dynamic_template_data: { first_name: "Yogesh"}, },
{ to: 'muthu@m2p.in',dynamic_template_data: { first_name: "Muthu"}, },
{ to: 'manikandan@m2p.in',dynamic_template_data: { first_name: "Manikandan Viswanathan"}, },
{ to: 'gokulkrishnan1986@gmail.com',dynamic_template_data: { first_name: "gokulkrishan1986"}, },
{ to: 'ftrepanier@efinancialcareers.com',dynamic_template_data: { first_name: "Francois"}, },
{ to: 'vijay@m2p.in',dynamic_template_data: { first_name: "Vijay Subramanian"}, },
{ to: 'madhu@m2p.in',dynamic_template_data: { first_name: "Madhusudanan"}, },
{ to: 'prateek2.jain@paytmbank.com',dynamic_template_data: { first_name: "Prateek"}, },
{ to: 'jack@m2p.in',dynamic_template_data: { first_name: "Antony Jackson"}, },
{ to: 'shanal.jauhari@rblbank.com',dynamic_template_data: { first_name: "Shanal"}, },
{ to: 'dinesh.singh2@yesbank.in',dynamic_template_data: { first_name: "dinesh.singh2@yesbank.in"}, },
{ to: 'archana@m2p.in',dynamic_template_data: { first_name: "Archana"}, },
{ to: 'ereports@yesbank.in',dynamic_template_data: { first_name: "ereports@yesbank.in"}, },
{ to: 'surbhi.suman@niiconsulting.com',dynamic_template_data: { first_name: "Surbhi"}, },
{ to: 'shyam@m2p.in',dynamic_template_data: { first_name: "Shyam Kumar"}, },
{ to: 'sonalib@federalbank.co.in',dynamic_template_data: { first_name: "SONALI"}, },
{ to: 'vivekg@federalbank.co.in',dynamic_template_data: { first_name: "Vivek"}, },
{ to: 'ganapathy.gy@gmail.com',dynamic_template_data: { first_name: "Ganapathy"}, },
{ to: 'sonu.sharma@paytmbank.com',dynamic_template_data: { first_name: "Sonu"}, },
{ to: 'rajkumar.bhatia@icicibank.com',dynamic_template_data: { first_name: "Rajkumar"}, },
{ to: 'siva@karins.in',dynamic_template_data: { first_name: "K,"}, },
{ to: 'sanjeev.agarwal@dvara.com',dynamic_template_data: { first_name: "Sanjeev"}, },
{ to: 'rajesh@highwaydelite.com',dynamic_template_data: { first_name: "Rajesh"}, },
{ to: 'kirthiga.k@tvscredit.com',dynamic_template_data: { first_name: "Kirthiga"}, },
{ to: 'acs_support@fss.co.in',dynamic_template_data: { first_name: "ACS_SUPPORT"}, },
{ to: 'siddharth.doshi@idfy.com',dynamic_template_data: { first_name: "Siddharth"}, },
{ to: 'sasikumari.vetrivelu@npci.org.in',dynamic_template_data: { first_name: "Sasikumari"}, },
{ to: 'manisha@gaiaq.com',dynamic_template_data: { first_name: "Manisha"}, },
{ to: 'saurav.goyal@moneyview.in',dynamic_template_data: { first_name: "Suarav"}, },
{ to: 'maulik.patel@npci.org.in',dynamic_template_data: { first_name: "Maulik"}, },
{ to: 'thirumaniraj.vamosys@gmail.com',dynamic_template_data: { first_name: "thirumaniraj"}, },
{ to: 'akumar@indifi.com',dynamic_template_data: { first_name: "Ashwini"}, },
{ to: 'ecomaxgo@gmail.com',dynamic_template_data: { first_name: "EcoMaxGo"}, },
{ to: 'offers@slidemodel.com',dynamic_template_data: { first_name: "SlideModel"}, },
{ to: 'aju.mehra@loconav.com',dynamic_template_data: { first_name: "Aju"}, },
{ to: 'narasimman@m2p.in',dynamic_template_data: { first_name: "Narasimman A"}, },
{ to: 'sriram.c@go-mmt.com',dynamic_template_data: { first_name: "Sriram"}, },
{ to: 'ksenthil@m2p.in',dynamic_template_data: { first_name: "Senthil Kumar Kanniappan"}, },
{ to: 'reshma.chothani@bookmyshow.com',dynamic_template_data: { first_name: "Reshma"}, },
{ to: 'ravi@safexpay.com',dynamic_template_data: { first_name: "Ravi"}, },
{ to: 'nidhi@storynmore.com',dynamic_template_data: { first_name: "Nidhi"}, },
{ to: 'dipesh@lendenclub.com',dynamic_template_data: { first_name: "Dipesh"}, },
{ to: 'kumari.komal@npci.org.in',dynamic_template_data: { first_name: "Kumari"}, },
{ to: 'satyam@bankopen.co',dynamic_template_data: { first_name: "Satyam"}, },
{ to: 'arun.kumar@mplgaming.com',dynamic_template_data: { first_name: "Arun"}, },
{ to: 'satheeshkumar.sukumar@lvbank.in',dynamic_template_data: { first_name: "Satheesh"}, },
{ to: 'ricky.kunder@yesbank.in',dynamic_template_data: { first_name: "ricky.kunder@yesbank.in"}, },
{ to: 'girish.parpillewar@sbmbank.co.in',dynamic_template_data: { first_name: "Girish"}, },
{ to: 'rameshvenkat@lsc-india.com',dynamic_template_data: { first_name: "rameshvenkat@lsc-india.com"}, },
{ to: 'thiyagarajan@m2p.in',dynamic_template_data: { first_name: "Thiyagarajan Chinnaiya"}, },
{ to: 'sandeep.mhatre@yesbank.in',dynamic_template_data: { first_name: "sandeep.mhatre@yesbank.in"}, },
{ to: 'ashish.morvekar@rblbank.com',dynamic_template_data: { first_name: "Ashish"}, },
{ to: 'bhushan.tuli@avanse.com',dynamic_template_data: { first_name: "Bhushan"}, },
{ to: 'bingle@colemanrg.com',dynamic_template_data: { first_name: "bingle@colemanrg.com"}, },
{ to: 'lalithkumarkj@fss.co.in',dynamic_template_data: { first_name: "Lalith"}, },
{ to: 'shahbaaz.quershi@axisbank.com',dynamic_template_data: { first_name: "Shahbaaz"}, },
{ to: 'mridula@federalbank.co.in',dynamic_template_data: { first_name: "MRIDULA"}, },
{ to: 'pb.sebastian@icicibank.com',dynamic_template_data: { first_name: "Sebastian"}, },
{ to: 'mdsg@federalbank.co.in',dynamic_template_data: { first_name: "Federal"}, },
{ to: 'mukundraj.kulkarni@tvscredit.com',dynamic_template_data: { first_name: "Mukundraj"}, },
{ to: 'mansi.kumar@neogrowth.in',dynamic_template_data: { first_name: "Mansi"}, },
{ to: 'jeeva@m2p.in',dynamic_template_data: { first_name: "Jeeva"}, },
{ to: 'easan@brokerage-free.com',dynamic_template_data: { first_name: "Easan"}, },
{ to: 'kuntal.pandya@axisbank.com',dynamic_template_data: { first_name: "Kuntal"}, },
{ to: 'nkuzhali@csb.co.in',dynamic_template_data: { first_name: "Kuzhali"}, },
{ to: 'mayank@moneyhop.co',dynamic_template_data: { first_name: "Mayank"}, },
{ to: 'chakri.prabhakar@aiaioo.com',dynamic_template_data: { first_name: "Chakri"}, },
{ to: 'pramod.bhaktha@mctcardstech.com',dynamic_template_data: { first_name: "Pramod"}, },
{ to: 'danial@m2p.me',dynamic_template_data: { first_name: "Danial"}, },
{ to: 'shamilchandanv@equitasbank.com',dynamic_template_data: { first_name: "shamil"}, },
{ to: 'saurabh.johri@finobank.com',dynamic_template_data: { first_name: "Saurabh"}, },
{ to: 'tanushri.yewale@neogrowth.in',dynamic_template_data: { first_name: "Tanushri"}, },
{ to: 'sathyanarayanan.gk@lvbank.in',dynamic_template_data: { first_name: "SATHYANARAYANAN"}, },
{ to: 'dheemant.thacker@ujjivan.com',dynamic_template_data: { first_name: "Dheemant"}, },
{ to: 'akshay.jain@panaceainfosec.com',dynamic_template_data: { first_name: "Akshay"}, },
{ to: 'sajal.khanna@akudo.in',dynamic_template_data: { first_name: "Sajal"}, },
{ to: 'nitin.parab@mytrux.com',dynamic_template_data: { first_name: "Nitin"}, },
{ to: 'msaravind@brokerage-free.com',dynamic_template_data: { first_name: "Mohana"}, },
{ to: 'balaharish.m@manipalgroup.info',dynamic_template_data: { first_name: "Balaharish"}, },
{ to: 'rakshit.shah@mswipe.in',dynamic_template_data: { first_name: "Rakshit"}, },
{ to: 'arunchandrasekaran83@outlook.com',dynamic_template_data: { first_name: "Arun"}, },
{ to: 'svenkat75@gmail.com',dynamic_template_data: { first_name: "Venkat"}, },
{ to: 'arindamdasgupta@equitasbank.com',dynamic_template_data: { first_name: "Arindamdas"}, },
{ to: 'shriraam@m2p.in',dynamic_template_data: { first_name: "Shriraam Jayaraman"}, },
{ to: 'chirag@mobaccs.in',dynamic_template_data: { first_name: "Chirag"}, },
{ to: 'rajkumar95ws@gmail.com',dynamic_template_data: { first_name: "Kumar"}, },
{ to: 's.ramesh@tvscredit.com',dynamic_template_data: { first_name: "Ramesh"}, },
{ to: 'pankaj@yatraangelnetwork.com',dynamic_template_data: { first_name: "Pankaj"}, },
{ to: 'posadmin@lvbank.in',dynamic_template_data: { first_name: "posadmin(Easwaramoorthy)"}, },
{ to: 'harman@gtropy.com',dynamic_template_data: { first_name: "Harman"}, },
{ to: 'gokul.kumar@myshubhlife.com',dynamic_template_data: { first_name: "Gokul"}, },
{ to: 'knmrao@quickride.in',dynamic_template_data: { first_name: "KNM"}, },
{ to: 'rkrithika@m2p.in',dynamic_template_data: { first_name: "Krithika Rajendran"}, },
{ to: 'senthil@vamosys.com',dynamic_template_data: { first_name: "SenthilKumar"}, },
{ to: 'amartya.biswas@idfcfirstbank.com',dynamic_template_data: { first_name: "Amartya"}, },
{ to: 'ajay@instantpay.in',dynamic_template_data: { first_name: "Ajay"}, },
{ to: 'rijulravi@csb.co.in',dynamic_template_data: { first_name: "Rijul"}, },
{ to: 'misha.maikhuri@npci.org.in',dynamic_template_data: { first_name: "Misha"}, },
{ to: 'girija@m2p.in',dynamic_template_data: { first_name: "Girija"}, },
{ to: 'vikas.srivastava@selp.in',dynamic_template_data: { first_name: "Vikas"}, },
{ to: 'mrunmay.dash@swiggy.in',dynamic_template_data: { first_name: "Mrunmay"}, },
{ to: 'umeshs@equitasbank.com',dynamic_template_data: { first_name: "Umesh"}, },
{ to: 'rupinder.sabharwal@eko.co.in',dynamic_template_data: { first_name: "Rupinder"}, },
{ to: 'balaji@m2p.in',dynamic_template_data: { first_name: "Balaji Narayanasamy"}, },
{ to: 'kartik@insight-kellton.com',dynamic_template_data: { first_name: "Kartik"}, },
{ to: 'devyash.goel@udaan.com',dynamic_template_data: { first_name: "Devyash"}, },
{ to: 'director@youthcouncilofindia.org',dynamic_template_data: { first_name: "TRUE"}, },
{ to: 'ramkumarr@fss.co.in',dynamic_template_data: { first_name: "Ramkumar"}, },
{ to: 'pavan.pai@manipalgroup.info',dynamic_template_data: { first_name: "Pavan"}, },
{ to: 'naveen@m2p.in',dynamic_template_data: { first_name: "Naveen Muthu Santha"}, },
{ to: 'rebecca.dsilva@kuliza.com',dynamic_template_data: { first_name: "Rebecca"}, },
{ to: 'mailer-daemon@googlemail.com',dynamic_template_data: { first_name: "Mail"}, },
{ to: 'daykin@go.ooo',dynamic_template_data: { first_name: "Daykin"}, },
{ to: 'jignesh.ashar@savvyapp.in',dynamic_template_data: { first_name: "Jignesh"}, },
{ to: 'bhagaban@walruspay.com',dynamic_template_data: { first_name: "bhagaban@walruspay.com"}, },
{ to: 'premkumars@fss.co.in',dynamic_template_data: { first_name: "Prem"}, },
{ to: 'himanshu.sahu@loconav.com',dynamic_template_data: { first_name: "Himanshu"}, },
{ to: 'sriharsha@walruspay.com',dynamic_template_data: { first_name: "Sriharsha"}, },
{ to: 'thilak@tripgain.com',dynamic_template_data: { first_name: "Thilak"}, },
{ to: 'arun.jaiswal@loconav.com',dynamic_template_data: { first_name: "Arun"}, },
{ to: 'udhayanan@bijlipay.co.in',dynamic_template_data: { first_name: "Udhayanan"}, },
{ to: 'no-reply@ettech.com',dynamic_template_data: { first_name: "ETtech"}, },
{ to: 'manikumar@m2p.in',dynamic_template_data: { first_name: "Mani Kumar"}, },
{ to: 'hari@m2p.in',dynamic_template_data: { first_name: "Hari Ramakrishna Parkar"}, },
{ to: 'adeshk@fss.co.in',dynamic_template_data: { first_name: "Adesh"}, },
{ to: 'pk@vamosys.com',dynamic_template_data: { first_name: "VAMO"}, },
{ to: 'nithin@zerodha.com',dynamic_template_data: { first_name: "Nithin"}, },
{ to: 'varun@upshot.ai',dynamic_template_data: { first_name: "Varun"}, },
{ to: 'swati.sanghvi.ext@yesbank.in',dynamic_template_data: { first_name: "swati.sanghvi.ext@yesbank.in"}, },
{ to: 'xceldevang@gmail.com',dynamic_template_data: { first_name: "Devang"}, },
{ to: 'it-procurements@equitasbank.com',dynamic_template_data: { first_name: "IT-Procurement"}, },
{ to: 'ranjini.rajkumar@qwikcilver.com',dynamic_template_data: { first_name: "Ranjini"}, },
{ to: 'sindhuja@m2p.in',dynamic_template_data: { first_name: "Sindhuja R"}, },
{ to: 'sivakumar.selvam@npci.org.in',dynamic_template_data: { first_name: "Sivakumar"}, },
{ to: 'arun.sreenivasan@ujjivan.com',dynamic_template_data: { first_name: "Arun"}, },
{ to: 'sanjay.bansode@veels.plus',dynamic_template_data: { first_name: "Sanjay"}, },
{ to: 'santhosprabahar@m2p.in',dynamic_template_data: { first_name: "Santhosh Prabaharan"}, },
{ to: 'noreply@email.teams.microsoft.com',dynamic_template_data: { first_name: "Naren"}, },
{ to: 'ashokan.arunachalam@icicibank.com',dynamic_template_data: { first_name: "Ashokan"}, },
{ to: 'comments-noreply@docs.google.com',dynamic_template_data: { first_name: "Madhusudanan"}, },
{ to: 'darshan@vauld.com',dynamic_template_data: { first_name: "Darshan"}, },
{ to: 'hemangi@payments2.com',dynamic_template_data: { first_name: "Hemangi"}, },
{ to: 'sidhu@m2p.in',dynamic_template_data: { first_name: "Sidhudevarayan"}, },
{ to: 'shyamkumar.nair@npci.org.in',dynamic_template_data: { first_name: "Shyamkumar"}, },
{ to: 'jegan@m2p.in',dynamic_template_data: { first_name: "Jegan Govindarajan"}, },
{ to: 'ritam.bhattacharjee@npci.org.in',dynamic_template_data: { first_name: "Ritam"}, },
{ to: 'aruna@m2p.in',dynamic_template_data: { first_name: "Aruna Priyanka Muthupandi"}, },
{ to: 'dinesh@m2p.in',dynamic_template_data: { first_name: "Dinesh R"}, },
{ to: 'deepak@quickride.in',dynamic_template_data: { first_name: "Deepak"}, },
{ to: 'ilakkiya@m2p.in',dynamic_template_data: { first_name: "Ilakkiya Prashanth"}, },
{ to: 'mittul.desai@razorpay.com',dynamic_template_data: { first_name: "Mittul"}, },
{ to: 'santhosh.p@rblbank.com',dynamic_template_data: { first_name: "Santhosh"}, },
{ to: 'vivek.kapur@spicemoney.com',dynamic_template_data: { first_name: "Vivek"}, },
{ to: 'crgdataacct@colemanrg.com',dynamic_template_data: { first_name: "CRG-Data"}, },
{ to: 'jyothi@m2p.in',dynamic_template_data: { first_name: "Jyothi Chinthapally"}, },
{ to: 'naveen@quickride.in',dynamic_template_data: { first_name: "Naveen"}, },
{ to: 'atish@m2p.in',dynamic_template_data: { first_name: "Atish"}, },
{ to: 'abhishek.roy@npci.org.in',dynamic_template_data: { first_name: "Abhishek"}, },
{ to: 'sanjay.gandhi@easyplan.in',dynamic_template_data: { first_name: "Sanjay"}, },
{ to: 'lavika.aggarwal@akudo.in',dynamic_template_data: { first_name: "Lavika"}, },
{ to: 'vaanathi@m2p.me',dynamic_template_data: { first_name: "Vaanathi"}, },
{ to: 'sachin.kp@qwikcilver.com',dynamic_template_data: { first_name: "Sachin"}, },
{ to: 'swapnil@freighttiger.com',dynamic_template_data: { first_name: "Swapnil"}, },
{ to: 'pranay.jha@icicibank.com',dynamic_template_data: { first_name: "Pranay"}, },
{ to: 'jegan.prasath@paynearby.in',dynamic_template_data: { first_name: "Jegan"}, },
{ to: 'sunil@m2p.me',dynamic_template_data: { first_name: "Sunil"}, },
{ to: 'saransh.sinyal@icicibank.com',dynamic_template_data: { first_name: "Saransh"}, },
{ to: 'vasanthj@m2p.in',dynamic_template_data: { first_name: "Vasantha Kumar Jayachandran"}, },
{ to: 'mansi@aadrila.com',dynamic_template_data: { first_name: "Mansi"}, },
{ to: 'anuragsengupta@csb.co.in',dynamic_template_data: { first_name: "Anurag"}, },
{ to: 'achint@riskcovry.com',dynamic_template_data: { first_name: "Achint"}, },
{ to: 'shivangi@newtonschool.co',dynamic_template_data: { first_name: "Shivangi"}, },
{ to: 'rajesh.wadhwa@m2p.in',dynamic_template_data: { first_name: "Rajesh Gurudas Wadhwa"}, },
{ to: 'hitesh.malhotra@idfcfirstbank.com',dynamic_template_data: { first_name: "Hitesh"}, },
{ to: 'info@vbn.visa.com',dynamic_template_data: { first_name: "Visa"}, },
{ to: 'desigan.gopal@npci.org.in',dynamic_template_data: { first_name: "Desigan"}, },
{ to: 'na@na.com',dynamic_template_data: { first_name: "test"}, },
{ to: 'alerts@yesbank.in',dynamic_template_data: { first_name: "alerts@yesbank.in"}, },
{ to: 'rajeshm@m2p.in',dynamic_template_data: { first_name: "Rajesh Manickam"}, },
{ to: 'yogesh@transin.in',dynamic_template_data: { first_name: "Yogesh"}, },
{ to: 'senthamizhselvan.s@tvscredit.com',dynamic_template_data: { first_name: "Senthamizhselvan"}, },
{ to: 'jenny@m2p.in',dynamic_template_data: { first_name: "Jenny Preethi"}, },
{ to: 'malhar.moghe@zencon.co.in',dynamic_template_data: { first_name: "malhar.moghe@zencon.co.in"}, },
{ to: 'events@postman.com',dynamic_template_data: { first_name: "The"}, },
{ to: 'adityaa@workadvantage.in',dynamic_template_data: { first_name: "Aditya"}, },
{ to: 'sekhar.rao@savvyapp.in',dynamic_template_data: { first_name: "sekhar.rao@savvyapp.in"}, },
{ to: 'etcops@icicibank.com',dynamic_template_data: { first_name: "etcops"}, },
{ to: 'noreply@zimyo.com',dynamic_template_data: { first_name: "Zimyo"}, },
{ to: 'mayank.aggarwal@transcorpint.com',dynamic_template_data: { first_name: "Mayank"}, },
{ to: 'samarjeet@m2p.in',dynamic_template_data: { first_name: "Samarjeet"}, },
{ to: 'venkatanagakalyani.m@tvscredit.com',dynamic_template_data: { first_name: "Venkata"}, },
{ to: 'pooja.shetty@mctcardstech.com',dynamic_template_data: { first_name: "Pooja"}, },
{ to: 'indranil.ain@rblbank.com',dynamic_template_data: { first_name: "Indranil"}, },
{ to: 'hello@indiafintech.com',dynamic_template_data: { first_name: "India"}, },
{ to: 'sarunavally@csb.co.in',dynamic_template_data: { first_name: "Arunavally"}, },
{ to: 'praveena@m2p.in',dynamic_template_data: { first_name: "Praveena"}, },
{ to: 'niket@m2p.in',dynamic_template_data: { first_name: "Niket Pramod Kumar Sharma"}, },
{ to: 'sandeepkh@federalbank.co.in',dynamic_template_data: { first_name: "Sandeep"}, },
{ to: 'agarwal.rajkamal@mahindra.com',dynamic_template_data: { first_name: "Rajkamal"}, },
{ to: 'saranya@m2p.in',dynamic_template_data: { first_name: "Saranya"}, },
{ to: 'rajeevsingh@kudosfinance.in',dynamic_template_data: { first_name: "Rajeev"}, },
{ to: 'praveen.kumar22@yesbank.in',dynamic_template_data: { first_name: "praveen.kumar22@yesbank.in"}, },
{ to: 'lokesh.ga@tvscredit.com',dynamic_template_data: { first_name: "Lokesh"}, },
{ to: 'imm.rajkumar@gmail.com',dynamic_template_data: { first_name: "Raj"}, },
{ to: 'sibikrish@brokerage-free.com',dynamic_template_data: { first_name: "Sibi"}, },
{ to: 'anusuyamythily.bfree@gmail.com',dynamic_template_data: { first_name: "ANUSUYA"}, },
{ to: 'shibupvarghese@csb.co.in',dynamic_template_data: { first_name: "Shibu"}, },
{ to: 'zyan@protectpay.in',dynamic_template_data: { first_name: "Zyan"}, },
{ to: 'faizan.saleem2812@gmail.com',dynamic_template_data: { first_name: "Faizan"}, },
{ to: 'sunil@karboncard.com',dynamic_template_data: { first_name: "Sunil"}, },
{ to: 'baghavathy.n@cityunionbank.in',dynamic_template_data: { first_name: "Baghavathy"}, },
{ to: 'dm@m2p.in',dynamic_template_data: { first_name: "Devang"}, },
{ to: 'sushyant.krishnan@rupeezen.com',dynamic_template_data: { first_name: "Sushyant"}, },
{ to: 'lakshmi@m2p.in',dynamic_template_data: { first_name: "Lakshmi Priya Janakiraman"}, },
{ to: 'hemalatha@m2p.in',dynamic_template_data: { first_name: "Hemalatha Sampath"}, },
{ to: 'harshal@apollofinvest.com',dynamic_template_data: { first_name: "Harshal"}, },
{ to: 'v.b@paypointindia.com',dynamic_template_data: { first_name: "V"}, },
{ to: 'vaa_vrm@visa.com',dynamic_template_data: { first_name: "VAA_VRM"}, },
{ to: 'no-reply@entertainment.bookmyshow.com',dynamic_template_data: { first_name: "BookMyShow"}, },
{ to: 'sandhya@m2p.in',dynamic_template_data: { first_name: "Sandhya"}, },
{ to: 'adwate@klubworks.com',dynamic_template_data: { first_name: "Adwate"}, },
{ to: 'balaji@tech.linq.store',dynamic_template_data: { first_name: "Balaji"}, },
{ to: 'maheshk@federalbank.co.in',dynamic_template_data: { first_name: "MAHESH"}, },
{ to: 'karthik.ks@ispirt.in',dynamic_template_data: { first_name: "Karthik"}, },
{ to: 'inderjeet.accounts@loconav.com',dynamic_template_data: { first_name: "Inderjeet"}, },
{ to: 'abhijithshetty@payments2.com',dynamic_template_data: { first_name: "Abhijith"}, },
{ to: 'samradha.tibrewala@bookmyshow.com',dynamic_template_data: { first_name: "Samradha"}, },
{ to: 'sourabh@advantageclub.in',dynamic_template_data: { first_name: "Sourabh"}, },
{ to: 'taco@trello.com',dynamic_template_data: { first_name: "Taco"}, },
{ to: 'suman@finin.in',dynamic_template_data: { first_name: "Suman"}, },
{ to: 'rahul.mahajan@rblbank.com',dynamic_template_data: { first_name: "Rahul"}, },
{ to: 'suganya@m2p.in',dynamic_template_data: { first_name: "Suganya"}, },
{ to: 'niraj.tralshawala@icicibank.com',dynamic_template_data: { first_name: "Niraj"}, },
{ to: 'kc@quickride.in',dynamic_template_data: { first_name: "Krishna"}, },
{ to: 'vasanth@fr8.in',dynamic_template_data: { first_name: "Vasanth"}, },
{ to: 'prachi.walake@sodelsolutions.com',dynamic_template_data: { first_name: "Prachi"}, },
{ to: 'nesar@m2p.in',dynamic_template_data: { first_name: "Nesar Ahmad"}, },
{ to: 'rajeev.agarwal@dvara.com',dynamic_template_data: { first_name: "Rajeev"}, },
{ to: 'vidhya@m2p.in',dynamic_template_data: { first_name: "Srividhya"}, },
{ to: 'alpsdeal@gmail.com',dynamic_template_data: { first_name: "Alps"}, },
{ to: 'vimalraj@m2p.in',dynamic_template_data: { first_name: "Vimal Raj"}, },
{ to: 'saran@walruspay.com',dynamic_template_data: { first_name: "Saran"}, },
{ to: 'akshay.chopra@livquik.com',dynamic_template_data: { first_name: "Aksay"}, },
{ to: 'soumava.chakraborty@sbi.co.in',dynamic_template_data: { first_name: "Soumava"}, },
{ to: 'rubesh@m2p.in',dynamic_template_data: { first_name: "SN RUBESH KUMAR"}, },
{ to: 'vivek@go.ooo',dynamic_template_data: { first_name: "Vivek"}, },
{ to: 'vasudevang@equitasbank.com',dynamic_template_data: { first_name: "Vasudevan"}, },
{ to: 'naren@brokerage-free.com',dynamic_template_data: { first_name: "Naren"}, },
{ to: 'deepanshu.tripathi@paytmbank.com',dynamic_template_data: { first_name: "Deepanshu"}, },
{ to: 'm-abhishek24.singh@ppbtp.com',dynamic_template_data: { first_name: "Abhishek24"}, },
{ to: 'arjun.kurane@yesbank.in',dynamic_template_data: { first_name: "Arjun"}, },
{ to: 'cjilna@csb.co.in',dynamic_template_data: { first_name: "Jilna"}, },
{ to: 'riyaz@godutchpay.in',dynamic_template_data: { first_name: "Riyaz"}, },
{ to: 'authsupport@uidai.gov.in',dynamic_template_data: { first_name: "Auth"}, },
{ to: 'teamzoom@zoom.us',dynamic_template_data: { first_name: "Zoom"}, },
{ to: 'suresh.jayamani@sbmbank.co.in',dynamic_template_data: { first_name: "Suresh"}, },
{ to: 'vishal@quickride.in',dynamic_template_data: { first_name: "vishal@quickride.in"}, },
{ to: 'vineet@fleetx.io',dynamic_template_data: { first_name: "Vineet"}, },
{ to: 'calendar-notification@google.com',dynamic_template_data: { first_name: "Google"}, },
{ to: 'neeraj.sinha@sbmbank.co.in',dynamic_template_data: { first_name: "Neeraj"}, },
{ to: 'hariprasath@m2p.in',dynamic_template_data: { first_name: "Hari Prasath"}, },
{ to: 'giftcard@federalbank.co.in',dynamic_template_data: { first_name: "giftcard@federalbank.co.in"}, },
{ to: 'anurakt@klubworks.com',dynamic_template_data: { first_name: "Anurakt"}, },
{ to: 'tushar.jadhao@ugrocapital.com',dynamic_template_data: { first_name: "Tushar"}, },
{ to: 'anil@m2p.in',dynamic_template_data: { first_name: "Anil"}, },
{ to: 'paresh.jethava@yesbank.in',dynamic_template_data: { first_name: "paresh.jethava@yesbank.in"}, },
{ to: 'shankar.raj@indianinfluencernetwork.com',dynamic_template_data: { first_name: "Shankar"}, },
{ to: 'kg@payspoon.com',dynamic_template_data: { first_name: "Kurian"}, },
{ to: 'bhawin@theinnovationinc.co',dynamic_template_data: { first_name: "Bhawin"}, },
{ to: 'shaktie@aadrila.com',dynamic_template_data: { first_name: "Shaktie"}, },
{ to: 'yashb@icloud.com',dynamic_template_data: { first_name: "Yash"}, },
{ to: 'maathavan@m2p.in',dynamic_template_data: { first_name: "Maathavan Thanu Ram Vinayak"}, },
{ to: 'karthik@zerodha.com',dynamic_template_data: { first_name: "Karthik"}, },
{ to: 'krishnan.s@sandasso.com',dynamic_template_data: { first_name: "krishnan.s"}, },
{ to: 'prepaid@csb.co.in',dynamic_template_data: { first_name: "prepaid@csb.co.in"}, },
{ to: 'catherine.anbarasi@npci.org.in',dynamic_template_data: { first_name: "Catherine"}, },
{ to: 'venkatramuj@equitasbank.com',dynamic_template_data: { first_name: "Venkatramu"}, },
{ to: 'abhinaya.venkatraman14@gmail.com',dynamic_template_data: { first_name: "Abhinaya"}, },
{ to: 'aditya@m2p.in',dynamic_template_data: { first_name: "Aditya Narasimhan"}, },
{ to: 'umamaheswari@m2p.in',dynamic_template_data: { first_name: "Umamaheswari Ramakrishnan"}, },
{ to: 'aniruddh@godutchpay.in',dynamic_template_data: { first_name: "Aniruddh"}, },
{ to: 'adarsh.tiwari@transcorpint.com',dynamic_template_data: { first_name: "ADARSH"}, },
{ to: 'rahul.patidar@moneyview.in',dynamic_template_data: { first_name: "Rahul"}, },
{ to: 'noreply@visa.com',dynamic_template_data: { first_name: "noreply@visa.com"}, },
{ to: 'rajkumaran@m2p.in',dynamic_template_data: { first_name: "Rajkumaran"}, },
{ to: 'neenaanand@csb.co.in',dynamic_template_data: { first_name: "Neena"}, },
{ to: 'sagar@godutchpay.in',dynamic_template_data: { first_name: "Sagar"}, },
{ to: 'balajip@m2p.in',dynamic_template_data: { first_name: "Balaji"}, },
{ to: 'rajakumaran@m2p.in',dynamic_template_data: { first_name: "Raj"}, },
{ to: 'anushka@go.ooo',dynamic_template_data: { first_name: "Anushka"}, },
{ to: 'jaya.sinha@paytmbank.com',dynamic_template_data: { first_name: "Jaya"}, },
{ to: 'srajagopalan@csb.co.in',dynamic_template_data: { first_name: "Rajagopalan"}, },
{ to: 'vijayakumar@m2p.in',dynamic_template_data: { first_name: "Vijayakumar Ganesan"}, },
{ to: 'abhishek.sharma@loconav.com',dynamic_template_data: { first_name: "Abhishek"}, },
{ to: 'service@townscript.com',dynamic_template_data: { first_name: "Townscript"}, },
{ to: 'sriharsha.setty@walruspay.com',dynamic_template_data: { first_name: "Sriharsha"}, },
{ to: 'pradeep.a@qwikcilver.com',dynamic_template_data: { first_name: "Pradeep"}, },
{ to: 'gautam@firstcry.com',dynamic_template_data: { first_name: "Gautam"}, },
{ to: 'vikram.aggarwal@payswiff.com',dynamic_template_data: { first_name: "Vikram"}, },
{ to: 'onkar.wadekar@shoppersstop.com',dynamic_template_data: { first_name: "Onkar"}, },
{ to: 'tejaswi@federalbank.co.in',dynamic_template_data: { first_name: "TEJASWI"}, },
{ to: 'gmohan@visa.com',dynamic_template_data: { first_name: "Mohan,"}, },
{ to: 'svelluthottam@kpmg.com',dynamic_template_data: { first_name: "svelluthottam@kpmg.com"}, },
{ to: 'zorawer.singh@stashfin.com',dynamic_template_data: { first_name: "Zorawer"}, },
{ to: 'lavanya@yappay.in',dynamic_template_data: { first_name: "Lavanya"}, },
{ to: 'info@transkwik.com',dynamic_template_data: { first_name: "TransKwik"}, },
{ to: 'bharathy.srinivasan@lvbank.in',dynamic_template_data: { first_name: "Bharathy"}, },
{ to: 'promo@ettech.com',dynamic_template_data: { first_name: "ETCIO"}, },
{ to: 'mehul.goenka@loconav.com',dynamic_template_data: { first_name: "Mehul"}, },
{ to: 'kumar@gritfirst.com',dynamic_template_data: { first_name: "Kumar"}, },
{ to: 'thiru@m2p.in',dynamic_template_data: { first_name: "Thirumoorthy Dharmalingam"}, },
{ to: 'netbanking@csb.co.in',dynamic_template_data: { first_name: "NET"}, },
{ to: 'info@slidemodel.com',dynamic_template_data: { first_name: "SlideModel"}, },
{ to: 'anandhipandi.r@ramco.com',dynamic_template_data: { first_name: "Anandhi"}, },
{ to: 'srajesh@m2p.in',dynamic_template_data: { first_name: "Rajesh"}, },
{ to: 'gaurav.yadav@npci.org.in',dynamic_template_data: { first_name: "Gaurav"}, },
{ to: 'info@visabusinessschool.visa.com',dynamic_template_data: { first_name: "Visa"}, },
{ to: 'priyanka@theinnovationinc.co',dynamic_template_data: { first_name: "Priyanka"}, },
{ to: 'sathish@m2p.in',dynamic_template_data: { first_name: "Sathish Vedhachalam"}, },
{ to: 'vibha.singh1@yesbank.in',dynamic_template_data: { first_name: "vibha.singh1@yesbank.in"}, },
{ to: 'newsletter@etprime.com',dynamic_template_data: { first_name: "ET"}, },
{ to: 'sunile@servion.com',dynamic_template_data: { first_name: "Sunil"}, },
{ to: 'bhupendra.mishra@ril.com',dynamic_template_data: { first_name: "Bhupendra"}, },
{ to: 'ayush.batra@colorplast.in',dynamic_template_data: { first_name: "Ayush"}, },
{ to: 'gagan.kochar@payenable.in',dynamic_template_data: { first_name: "Gagan"}, },
{ to: 'mmanikan@visa.com',dynamic_template_data: { first_name: "Manikandan,"}, },
{ to: 'pramod.sagar@npci.org.in',dynamic_template_data: { first_name: "Pramod"}, },
{ to: 'jagadish.krishnamurthy@qwikcilver.com',dynamic_template_data: { first_name: "Jagadish"}, },
{ to: 'eniyan@bijlipay.co.in',dynamic_template_data: { first_name: "Eniyan"}, },
{ to: 'siddharth.rastogi@idemia.com',dynamic_template_data: { first_name: "Siddharth"}, },
{ to: 'noreply@wetransfer.com',dynamic_template_data: { first_name: "WeTransfer"}, },
{ to: 'rahul@shubhloans.com',dynamic_template_data: { first_name: "Rahul"}, },
{ to: 'netcsupport@npci.org.in',dynamic_template_data: { first_name: "NETC"}, },
{ to: 'anto@m2p.in',dynamic_template_data: { first_name: "Anto Cruz Stephen"}, },
{ to: 'no-reply@zoom.us',dynamic_template_data: { first_name: "Zoom"}, },
{ to: 'tahem@nolobank.com',dynamic_template_data: { first_name: "Tahem"}, },
{ to: 'balakrishnan.ss@tvscredit.com',dynamic_template_data: { first_name: "Balakrishnan"}, },
{ to: 'posvendor@cityunionbank.in',dynamic_template_data: { first_name: "POSVENDOR"}, },
{ to: 'mehekka.oberoi@iifl.com',dynamic_template_data: { first_name: "Mehekka"}, },
{ to: 'nikhil.garg@dmifinance.in',dynamic_template_data: { first_name: "Nikhil"}, },
{ to: 'sundar@m2p.in',dynamic_template_data: { first_name: "Sundaravenkataraman Sundararaman"}, },
{ to: 'jayanthi@m2p.in',dynamic_template_data: { first_name: "Jayanthi Tharmaraj"}, },
{ to: 'chiranth@riskcovry.com',dynamic_template_data: { first_name: "Chiranth"}, },
{ to: 'iti.srivastava@selp.in',dynamic_template_data: { first_name: "Iti"}, },
{ to: 'srinath@m2p.in',dynamic_template_data: { first_name: "Srinath E S"}, },
{ to: 'ajeesh@bankope.co',dynamic_template_data: { first_name: "Ajeesh"}, },
{ to: 'praveen@pincap.in',dynamic_template_data: { first_name: "Praveen"}, },
{ to: 'kiran.karekar@yesbank.in',dynamic_template_data: { first_name: "kiran.karekar@yesbank.in"}, },
{ to: 'deepti@kodo.in',dynamic_template_data: { first_name: "Deepti"}, },
{ to: 'ac.alpsdeal@gmail.com',dynamic_template_data: { first_name: "Accounts"}, },
{ to: 'vroon@sokin.net',dynamic_template_data: { first_name: "Vroon"}, },
{ to: 'parvathanenia@equitasbank.com',dynamic_template_data: { first_name: "P"}, },
{ to: 'akashk3669@gmail.com',dynamic_template_data: { first_name: "Akash"}, },
{ to: 'sanket.kate@yesbank.in',dynamic_template_data: { first_name: "sanket.kate@yesbank.in"}, },
{ to: 'manya.mehra@trustingsocial.com',dynamic_template_data: { first_name: "Manya"}, },
{ to: 'priyank@godutchpay.in',dynamic_template_data: { first_name: "Priyank"}, },
{ to: 'chirag.kothari@paypoinntindia.com',dynamic_template_data: { first_name: "Chirag"}, },
{ to: 'akshaya@m2p.in',dynamic_template_data: { first_name: "Akshaya Chandrasekar"}, },
{ to: 'aastha@m2p.in',dynamic_template_data: { first_name: "Aastha"}, },
{ to: 'balachander.k@ntcgroup.in',dynamic_template_data: { first_name: "Balachander"}, },
{ to: 'postman-team@email.postman.com',dynamic_template_data: { first_name: "The"}, },
{ to: 'karthick@m2p.in',dynamic_template_data: { first_name: "Karthick Muthuswamy"}, },
{ to: 'logesh@m2p.in',dynamic_template_data: { first_name: "Logesh Kumar Kirubakaran"}, },
{ to: 'anish@bankopn.co',dynamic_template_data: { first_name: "Anish"}, },
{ to: 'sundaramanikandan@m2p.in',dynamic_template_data: { first_name: "Sundara Manikandan"}, },
{ to: 'annie@m2p.me',dynamic_template_data: { first_name: "Annie"}, },
{ to: 'bhupendra@paypointindia.com',dynamic_template_data: { first_name: "Bhupendra"}, },
{ to: 'mohansharmamvp@equitasbank.com',dynamic_template_data: { first_name: "Mohan"}, },
{ to: 'riyaz@m2p.in',dynamic_template_data: { first_name: "Mohammed Riyazuddin"}, },
{ to: 'sanjeevi@m2p.in',dynamic_template_data: { first_name: "Sanjeevi Sekar"}, },
{ to: 'sunil.s.m@kotak.com',dynamic_template_data: { first_name: "sunil.s.m@kotak.com"}, },
{ to: 'asish.keshri@icicibank.com',dynamic_template_data: { first_name: "Asish"}, },
{ to: 'shweta@m2p.in',dynamic_template_data: { first_name: "Shweta"}, },
{ to: 'dashiell.lipscomb@sokin.net',dynamic_template_data: { first_name: "Dashiell"}, },
{ to: 'ragav@m2p.in',dynamic_template_data: { first_name: "Ragavandharan Sundararaman"}, },
{ to: 'nakul@walruspay.com',dynamic_template_data: { first_name: "nakul@walruspay.com"}, },
{ to: 'a_priscilla@equitasbank.com',dynamic_template_data: { first_name: "Priscilla"}, },
{ to: 'craig.lewis@go.ooo',dynamic_template_data: { first_name: "Craig"}, },
{ to: 'nitesh@m2p.in',dynamic_template_data: { first_name: "Nitesh"}, },
{ to: 'neha@transcorpint.com',dynamic_template_data: { first_name: "neha@transcorpint.com"}, },
{ to: 'mayank.a@kinaracapital.com',dynamic_template_data: { first_name: "Mayank"}, },
{ to: 'lrajesh@m2p.in',dynamic_template_data: { first_name: "Rajesh L"}, },
{ to: 'naveen.chaluvadi1@yesbank.in',dynamic_template_data: { first_name: "Naveen"}, },
{ to: 'vimalkumar@m2p.in',dynamic_template_data: { first_name: "VimalKumaar Manohar"}, },
{ to: 'abhishek@m2p.in',dynamic_template_data: { first_name: "Abhishek"}, },
{ to: 'prakash.lal@finobank.com',dynamic_template_data: { first_name: "L"}, },
{ to: 'raghul@m2p.in',dynamic_template_data: { first_name: "Raghul Sathurappan"}, },
{ to: 'sivaramprasadk@equitasbank.com',dynamic_template_data: { first_name: "Sivaramprasad"}, },
{ to: 'shruti@m2p.in',dynamic_template_data: { first_name: "Shruti Devang Mehta"}, },
{ to: 'jebinkalliath@csb.co.in',dynamic_template_data: { first_name: "jebinkalliath@csb.co.in"}, },
{ to: 'no-reply@loconav.com',dynamic_template_data: { first_name: "no-reply@loconav.com"}, },
{ to: 'gayathri@m2p.in',dynamic_template_data: { first_name: "Gayathri"}, },
{ to: 'team@raconteur.vn',dynamic_template_data: { first_name: "Chau"}, },
{ to: 'sudharsan@shubhloans.com',dynamic_template_data: { first_name: "Sudhrsan"}, },
{ to: 'vijayp@m2p.in',dynamic_template_data: { first_name: "Vijay Padmanabhan Iyer"}, },
{ to: 'no-reply@sharepointonline.com',dynamic_template_data: { first_name: "SharePoint"}, },
{ to: 'shiny.ravi@npci.org.in',dynamic_template_data: { first_name: "Shiny"}, },
{ to: 'naveenkumar@m2p.in',dynamic_template_data: { first_name: "Naveen Kumar Angamuthu"}, },
{ to: 'sivakumar.v@cityunionbank.in',dynamic_template_data: { first_name: "sivakumar.v"}, },
{ to: 'ryana@kashware.com',dynamic_template_data: { first_name: "Ryan"}, },
{ to: 'akbar@aadrila.com',dynamic_template_data: { first_name: "Akbar"}, },
{ to: 'goutham@m2p.in',dynamic_template_data: { first_name: "Goutham Arunagiri"}, },
{ to: 'vishnu@walruspay.com',dynamic_template_data: { first_name: "Vishnu"}, },
{ to: 'albeprawlince@kaleyra.com',dynamic_template_data: { first_name: "Albert"}, },
{ to: 'ngupta@panaceainfosec.com',dynamic_template_data: { first_name: "Nandini"}, },
{ to: 'rajesh.singh@payu.in',dynamic_template_data: { first_name: "Rajesh"}, },
{ to: 'venkat@m2p.in',dynamic_template_data: { first_name: "Venkatesh Balaseharan"}, },
{ to: 'vivek@m2p.in',dynamic_template_data: { first_name: "Vivek Prashanth Nattar"}, },
{ to: 'pavan@zuqo.io',dynamic_template_data: { first_name: "Pavan"}, },
{ to: 'makarand.kelkar@idfcfirstbank.com',dynamic_template_data: { first_name: "Makarand"}, },
{ to: 'manjinder.kaur@perfectrfid.com',dynamic_template_data: { first_name: "Manjinder"}, },
{ to: 'viswesh@m2p.in',dynamic_template_data: { first_name: "Viswesh"}, },
{ to: 'mbs@payswiff.com',dynamic_template_data: { first_name: "Maulik"}, },
{ to: 'dhruba.das@icicibank.com',dynamic_template_data: { first_name: "Dhruba"}, },
{ to: 'anuj@vahan.co',dynamic_template_data: { first_name: "Anuj"}, },
{ to: 'info@indiafintech.co.in',dynamic_template_data: { first_name: "India"}, },
{ to: 'atul@worthpaisa.com',dynamic_template_data: { first_name: "Atul"}, },
{ to: 'manisha.pandita@easyplan.in',dynamic_template_data: { first_name: "Manisha"}, },
{ to: 'jose@m2p.in',dynamic_template_data: { first_name: "Jose Selvaraj Muthuramalingam"}, },
{ to: 'krishna@mplgaming.com',dynamic_template_data: { first_name: "Krishna"}, },
{ to: 'narayan.s@qwikcilver.com',dynamic_template_data: { first_name: "Narayan"}, },
{ to: 'prjohn@indianoil.in',dynamic_template_data: { first_name: "Premraj"}, },
{ to: 'vaishnavi@doodleblue.com',dynamic_template_data: { first_name: "Vaishnavi"}, },
{ to: 'vikrant.lele@swiggy.in',dynamic_template_data: { first_name: "Vilkrant"}, },
{ to: 'aniket.pathak@rblbank.com',dynamic_template_data: { first_name: "Aniket"}, },
{ to: 'bharathmani@csb.co.in',dynamic_template_data: { first_name: "Bharath"}, },
{ to: 'noreply@google.com',dynamic_template_data: { first_name: "Google"}, },
{ to: 'sreeram@linq.store',dynamic_template_data: { first_name: "Sreeram"}, },
{ to: 'kishore.kumar@qwikcilver.com',dynamic_template_data: { first_name: "Kishore"}, },
{ to: 'mahendra@shikshainfotech.com',dynamic_template_data: { first_name: "mahendra@shikshainfotech.com"}, },
{ to: 'argho.chatterjee@neogrowth.in',dynamic_template_data: { first_name: "Argho"}, },
{ to: 'navaneetkumar.singh@yesbank.in',dynamic_template_data: { first_name: "navaneetkumar.singh@yesbank.in"}, },
{ to: 'amol@instantpay.in',dynamic_template_data: { first_name: "Amol"}, },
{ to: 'ashokkumar.t@novopay.in',dynamic_template_data: { first_name: "Ashok"}, },
{ to: 'jose.annie@tvscredit.com',dynamic_template_data: { first_name: "Jose"}, },
{ to: 'arulnaveen@m2p.in',dynamic_template_data: { first_name: "Arul Naveen Micheal Raj"}, },
{ to: 'nicholas.belmont@tbp.global',dynamic_template_data: { first_name: "Nicholas"}, },
{ to: 'achla.choudhary@neogrowth.in',dynamic_template_data: { first_name: "Achla"}, },
{ to: 'dhruv.vashisht@loconav.com',dynamic_template_data: { first_name: "Dhruv"}, },
{ to: 'rohit.sarwate@neogrowth.in',dynamic_template_data: { first_name: "Rohit"}, },
{ to: 'nilendra.manval@yesbank.in',dynamic_template_data: { first_name: "Nilendra"}, },
{ to: 'arnabkrishna.ghosh@icicibank.com',dynamic_template_data: { first_name: "Arnab"}, },
{ to: 'nivedita.sen@livquik.com',dynamic_template_data: { first_name: "Nivedita"}, },
{ to: 'chinchu@federalbank.co.in',dynamic_template_data: { first_name: "CHINCHU"}, },
{ to: 'tickets@townscript.com',dynamic_template_data: { first_name: "Townscript"}, },
{ to: 'revathy@m2p.in',dynamic_template_data: { first_name: "Revathy"}, },
{ to: 'qc.intmessenger-noreply@qwikcilvermail.com',dynamic_template_data: { first_name: "qc.intmessenger-noreply@qwikcilvermail.com"}, },
{ to: 'bhanuprathap@bijlipay.co.in',dynamic_template_data: { first_name: "Bhanu"}, },
{ to: 'vrushali.deo@zencon.co.in',dynamic_template_data: { first_name: "Vrushali"}, },
{ to: 'trueandhealthroom7@youthcouncilofindia.org',dynamic_template_data: { first_name: "TRUE"}, },
{ to: 'bala@m2p.in',dynamic_template_data: { first_name: "Balakrishnan Elumalai"}, },
{ to: 'kgharekh@visa.com',dynamic_template_data: { first_name: "Gharekhan,"}, },
{ to: 'nitin.chaudhari@veels.plus',dynamic_template_data: { first_name: "Nitin"}, },
{ to: 'sanjana@astiinfotech.com',dynamic_template_data: { first_name: "sanjana@astiinfotech.com"}, },
{ to: 'rhemalatha@csb.co.in',dynamic_template_data: { first_name: "rhemalatha@csb.co.in"}, },
{ to: 'aman@safexpay.com',dynamic_template_data: { first_name: "Aman"}, },
{ to: 'ritesh.g@kinaracapital.com',dynamic_template_data: { first_name: "Ritesh"}, },
{ to: 'anshu.trivedi@sc.com',dynamic_template_data: { first_name: "Trivedi,"}, },
{ to: 'kumaran@m2p.in',dynamic_template_data: { first_name: "Kumaran"}, },
{ to: 'sanjay@moneyview.in',dynamic_template_data: { first_name: "Sanjay"}, },
        
        
      ]



};




sgMail.send(msg).catch(err => {
  console.log(err);
});